version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT_HTTP=3000
    ports:
      - 3000:3000
    expose:
      - 3000
